name: enough_media
description: Extensible collection of media viewers for preview and interactive experiences.
version: 2.2.2
homepage: https://github.com/enough-software/enough_media
topics:
 - media
 - viewer
 - pdf
 - photo
 - video
 - audio

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  chewie: ^1.7.0
  chewie_audio: ^1.5.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  pdfx: ^2.5.0
  photo_view: ^0.14.0
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter.
flutter:

