name: enough_media
description: Extensible collection of media viewers for preview and interactive experiences.
version: 2.3.0
homepage: https://github.com/enough-software/enough_media
topics:
 - media
 - pdf
 - photo
 - video
 - audio

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  chewie: ^1.8.0
  chewie_audio: ^1.5.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  pdfx: ^2.6.0
  photo_view: ^0.14.0
  video_player: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

